<a href="https://colab.research.google.com/github/HimanshuSaini819/-Python-Assignment/blob/main/NUMPY_BASICS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import numpy as np

In [87]:
np.__version__

'1.26.4'

In [88]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [89]:
l=[1,2,3,4,5]

In [90]:
arr = np.array(l)

In [91]:
arr

array([1, 2, 3, 4, 5])

In [92]:
type(np.array(l))

numpy.ndarray

In [93]:
arr.ndim

1

In [94]:
l=[1,2,3,4,5,"rishi"]
arr1=np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'rishi'], dtype='<U21')

In [95]:
arr1.ndim

1

In [96]:
arr

array([1, 2, 3, 4, 5])

In [97]:
arr1=np.array([[1,2,3],[4,5,6]])

In [98]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
arr1.ndim

2

In [100]:
l=[1,2,3,4]

In [101]:
np.array(l)

array([1, 2, 3, 4])

In [102]:
mat=np.matrix(l) #matris will be by default 2d

In [103]:
np.matrix([[[1,2],[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [ ]:
np.array([[[2,3],[5,6],[7,8]]])

In [104]:
#more way to convert to array
np.asarray([[[2,3],[5,6],[7,8]]])

array([[[2, 3],
        [5, 6],
        [7, 8]]])

In [105]:
 np.asanyarray([[1,2],[5,6],[7,8]]) #convert the input to an ndarray,put pass ndarray through.

array([[1, 2],
       [5, 6],
       [7, 8]])

In [106]:
mat

matrix([[1, 2, 3, 4]])

In [107]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [108]:
np.asarray([[1,2],[5,6],[7,8]])

array([[1, 2],
       [5, 6],
       [7, 8]])

In [109]:
np.array([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [110]:
t=([1,2,3],[4,5,6])

In [111]:
type(t)

tuple

In [112]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
a=5
np.array(a)

array(5)

In [114]:

l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [115]:
a=arr

In [116]:
a

array([1, 2, 3, 4, 5])

In [117]:
arr[0]

1

In [118]:
arr[0]=1000

In [119]:
arr

array([1000,    2,    3,    4,    5])

In [120]:
a

array([1000,    2,    3,    4,    5])

In [121]:
b=a.copy()
b[0]=2000

In [122]:
b

array([2000,    2,    3,    4,    5])

In [123]:
a

array([1000,    2,    3,    4,    5])

In [124]:
#to create array>>.array,.asarray,.asanyarray,deep copy,shallow copy

In [125]:
#there are multipal way to gentrating array

In [126]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [127]:
arr

array([1000,    2,    3,    4,    5])

In [128]:
arr.shape

(5,)

In [129]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [130]:
arr1.shape

(2, 3)

In [131]:
arr.size

5

In [132]:
arr1.size


6

In [133]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [134]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [135]:
for i in range(5):
  print(i)

0
1
2
3
4


In [136]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [137]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [138]:
iterable=(i*i for i in range(5))

In [139]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [140]:
np.fromstring('23 34 67',sep ='')

<ipython-input-140-2a2f029649ae>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring('23 34 67',sep ='')


array([9.92155029e-43])

In [141]:
np.fromstring('suhani,ajay,anwesha',sep=',')

<ipython-input-141-1559fd8f9872>:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring('suhani,ajay,anwesha',sep=',')


array([], dtype=float64)

In [142]:
arr

array([1000,    2,    3,    4,    5])

In [143]:
arr.size

5

In [144]:
arr.shape

(5,)

In [145]:
arr.dtype

dtype('int64')

In [146]:
l=[1,2,3,"ajay"]
arr=np.array(l)
arr.dtype

dtype('<U21')

In [147]:
arr

array(['1', '2', '3', 'ajay'], dtype='<U21')

In [148]:
list(range(5))

[0, 1, 2, 3, 4]

In [149]:
range(5)

range(0, 5)

In [154]:
list(range(1.0,2.10))

TypeError: 'float' object cannot be interpreted as an integer

In [156]:
list(np.arange(0.1,10.2,0.1))

[0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3000000000000003,
 1.4000000000000001,
 1.5000000000000002,
 1.6,
 1.7000000000000002,
 1.8000000000000003,
 1.9000000000000001,
 2.0,
 2.1,
 2.2,
 2.3000000000000003,
 2.4000000000000004,
 2.5000000000000004,
 2.6,
 2.7,
 2.8000000000000003,
 2.9000000000000004,
 3.0000000000000004,
 3.1,
 3.2,
 3.3000000000000003,
 3.4000000000000004,
 3.5000000000000004,
 3.6,
 3.7,
 3.8000000000000003,
 3.9000000000000004,
 4.0,
 4.1,
 4.2,
 4.3,
 4.3999999999999995,
 4.5,
 4.6,
 4.7,
 4.8,
 4.9,
 5.0,
 5.1,
 5.2,
 5.3,
 5.4,
 5.5,
 5.6,
 5.7,
 5.8,
 5.9,
 6.0,
 6.1,
 6.2,
 6.3,
 6.4,
 6.5,
 6.6,
 6.7,
 6.8,
 6.9,
 7.0,
 7.1,
 7.2,
 7.3,
 7.4,
 7.5,
 7.6,
 7.7,
 7.8,
 7.9,
 8.0,
 8.1,
 8.2,
 8.3,
 8.4,
 8.5,
 8.6,
 8.7,
 8.8,
 8.9,
 9.0,
 9.1,
 9.2,
 9.3,
 9.4,
 9.5,
 9.6,
 9.700000000000001,
 9.8,
 9.9,
 10.0,
 10.1]

In [157]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [158]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [159]:
np.logspace(1,5,10,base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [161]:
arr1=np.zeros(5)
arr1.shape

(5,)

In [162]:
arr1

array([0., 0., 0., 0., 0.])

In [163]:
arr1.ndim

1

In [164]:
arr2=np.zeros((3,4))
arr2.shape

(3, 4)

In [165]:
aar2

NameError: name 'aar2' is not defined

In [166]:
arr2.ndim

2

In [168]:
arr3=np.zeros((1,3,4))
arr3.shape

(1, 3, 4)

In [169]:
arr3.ndim

3

In [172]:
arr4=np.zeros((1,1,3,4))
arr4.shape

(1, 1, 3, 4)

In [173]:
arr4.ndim

4

In [174]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [176]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [178]:
arr=np.ones((3,4))

In [179]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [180]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [181]:
arr*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [182]:
np.array([[[[[[[[[[[[[[[[[[[[[1,1,1,1,]]]]]]]]]]]]]]]]]]]]])

array([[[[[[[[[[[[[[[[[[[[[1, 1, 1, 1]]]]]]]]]]]]]]]]]]]]])

In [183]:
np.tows((2,3))

AttributeError: module 'numpy' has no attribute 'tows'

In [184]:
l=[1,2,3,4,5,"prince"]
arr=np.array(l)
arr.dtype

dtype('<U21')

In [185]:
arr

array(['1', '2', '3', '4', '5', 'prince'], dtype='<U21')